### ISSUE TITLE
Make score board

### ISSUE THREAD

**Issue by han-byul-yang** [gogoyong/pigthedice#5]
# Contents
Pig the dice game의 각 개인의 점수판 제작 

# Task lists
- [ ] 각 플레이어의 이름과 각 라운드 별 점수판 만들기
- [ ] 라운드 마다 각 플레이어가 던진 주사위의 숫자와 결과를 입력
-        숫자 2-6이 나오면 점수 추가, 숫자 1이 나오면 초기화
- [ ] 플레이어 중 점수 합 100이 나오면 라운드 종료 표시
